Vagrant.configure("2") do |config|
    config.vm.box = "Ubuntu precise 64 VMWare"
    config.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"

    config.vm.define "eventstore" do |eventstore|
        eventstore.vm.network "private_network", ip: "192.168.50.11"
        eventstore.vm.network :forwarded_port, guest: 2113, host: 2113
        eventstore.vm.provision :shell, :path => "../setup/single-bootstrap.sh"
    end
end 
